Add support for Python 3.11
conda-forge/sktime-feedstock pull request #65
Opened 2023-02-21 14:13 UTC by giswqs

The upstream supports [">=3.7,<3.12"](https://github.com/sktime/sktime/blob/19618df351a27b77e3979efc191e53987dbd99ae/pyproject.toml#L41), we should add support for Python 3.11. 

Addressing issue https://github.com/sktime/sktime/issues/4254#issuecomment-1438554815

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2023-02-21 14:13 UTC, giswqs commented
@conda-forge-admin, please rerender

2023-02-21 14:14 UTC, fkiraly approved these changes
Thank you very much (and obviously also for https://github.com/conda-forge/sktime-feedstock/pull/64) !

2023-02-21 23:27 UTC, dhirschfeld commented
@fkiraly - as an upstream maintainer you should feel free to merge here whenever you see fit. It helps to keep a good development velocity and if any issues do arise they can be easily fixed on `main`.

2023-02-21 23:28 UTC, dhirschfeld commented
@conda-forge-admin, please rerender

2023-02-21 23:29 UTC, dhirschfeld commented
> feel free to merge here whenever you see fit

...though it doesn't seem to be building for py311 🤔

2023-02-21 23:32 UTC, giswqs commented
Yeah, not sure why the rerender doesn't trigger the build for Python 3.11

2023-02-21 23:45 UTC, dhirschfeld commented
I think we need to add it to the `py311` migration to get the bot to add the necessary CI files
* https://conda-forge.org/status/#python311

It seems to be there in Awaiting Parents so I guess we have to wait until all the deps are built for `py311`.

2023-02-22 00:02 UTC, fkiraly requested changes
I see. I'm unfortunately not too familiar with this azure based workflow.
Would appreciate a quick pointer how I can see which deps are not building.

The problem could possibly be `numba`. If it is a dep, it will not build since it does not exist on 3.11. The trick is to make it a dep only if python<=3.10.

2023-02-22 00:03 UTC, fkiraly commented
> as an upstream maintainer you should feel free to merge here whenever you see fit.

Well, I was wondering what was going on and put it aside...

2023-02-22 00:06 UTC, fkiraly commented
So I suppose the magic tagging of conda-smity is supposed to trigger a workflow that populates the `.azure-pipelines` and other dot folders in this branch, correct? And it doesn't, and that's the problem?

Can you confirm (or correct) my understanding?

2023-02-22 00:28 UTC, dhirschfeld commented
The bot should automatically open a PR to migrate this repo to `py311` when all the dependencies of `sktime` are available.

As you say, `numba` doesn't work on `py311` yet so *at least* that will be a problem.

If it's possible to make it an optional dependency then you could publish a version without it and, if that were the only problem, it might trigger the bot to make the migration PR.

Alternatively, you could just wait for all the deps to be available.
* https://github.com/numba/numba/issues/8304

2023-02-22 00:34 UTC, dhirschfeld commented
If this feedstock is constrained to `py<311` it might prevent the bot from making the migration PR so my plan of attack is to merge this and wait.

If you desperately need this on `py311` now you can put in another PR to make `numba` an optional dependency (if indeed it will work without it).

2023-02-22 01:28 UTC, merged

2023-02-22 11:45 UTC, fkiraly commented
> (if indeed it will work without it).

Yes, `sktime` from 0.16.1 on works without `numba` on all versions, as the dependency has been isolated (imports moved into functions, classes etc)

2023-02-22 12:33 UTC, dhirschfeld commented
> Yes, `sktime` from 0.16.1 on works without `numba` on all versions, as the dependency has been isolated (imports moved into functions, classes etc)

I guess there's a fairly strong argument that you shouldn't be forcing users to install dependencies they don't need/use. If `sktime` is severely limited by not having `numba` available it might be equally bad to have the *default* install be a crippled version of `sktime`.

I think the usual way around this is to provide a `sktime-base` package with the absolute minimum dependencies required for basic functionality with `sktime` being a meta-package which required `sktime-base` plus the usual dependencies to get a reasonable UX.

2023-02-22 22:29 UTC, fkiraly commented
@dhirschfeld, `numba` is not needed except for some estimators, no base functionality is really crippled. It has just been badly managed in terms of dependency isolation, most work in 0.16.1 is a clean-up of dependency management.

It would not be needed for any version, but due to the deprecation policy we need to wait for 0.18.0 to remove it as a core dependency.